spring:
    application:
        name: ops-gate
    thymeleaf:
        mode: LEGACYHTML5
        cache: false
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
        default-property-inclusion: non_null
    #redis:
    #    database: 1
    #    host: ${redis.host:10.180.8.220}
    #    pool:
    #        max-active: 20
    datasource:
       driverClassName: com.mysql.jdbc.Driver
       url: ${db.yc_base.url:jdbc:mysql://10.180.8.205:3306/yc_base?useUnicode=true&amp;characterEncoding=utf8mb4}
       username: ${db.yc_base.username:root}
       password: ${db.yc_base.pwd:rcs}
server:
    port: ${ops.gate.port:8766} #启动端口

ajpport: 9101
jvmroute: ""

#
zuul:
  ignored-services: "*"
  sensitive-headers:
  sensitiveHeaders: 
  prefix: /api #为zuul设置一个公共的前缀
  ratelimit: # 网关限流
    key-prefix: gate_rate
    enabled: true
    repository: IN_MEMORY #REDIS, JPA, IN_MEMORY
    behind-proxy: true
    default-policy: #optional - will apply unless specific policy exists
      limit: 600
      refresh-interval: 60 #default value (in seconds)
      type: #optional
        - user
        - origin
        - url
  routes:
    back:
      path: /admin/**
      serviceId: ops-admin
    auth:
      path: /auth/**
      serviceId: ops-auth
    manager:
      path: /manager/**
      serviceId: ops-admin
    captcha:
      path: /captcha/**
      serviceId: ops-auth
      strip-prefix: false
    wechat:
      path: /wechat/**
      serviceId: wechat-service
    message:
      path: /message/**
      serviceId: ops-mq
    service:
      path: /service/**
      serviceId: ops-service 
    task:
      path: /task/**
      serviceId: ops-task
  host: 
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
      
      
  store:
    mysql:
      enabled: true

  db:
    name: test
    url: ${db.yc_base.url:jdbc:mysql://10.180.8.205:3306/yc_base?useUnicode=true&amp;characterEncoding=utf8mb4}
    username: ${db.yc_base.username:root}
    password: ${db.yc_base.pwd:rcs}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    basepackage: com.yonyou.cloud.zuul.db.mapper
    xmlLocation: classpath:mapper/**/*.xml
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  OkToRetryOnAllOperations: false


hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000


gate:
  ignore:
    startWith: /static,/auth/jwt,/captcha/jwt

logging:
  level:
    root: info
auth:
  serviceId: ops-auth
  user:
    token-header: Authorization ##所有业务的请求头使用这个来传递JWT
    pub-key:
      path: jwt/pub.key
  client:
    token-header: client-token
    id: ace-gate  #不填则默认读取spring.application.name
    secret: 123456
    pub-key:
      path: client/pub.key
groovy:
  filter:
    path: ${groovy.path:D:\\Del\\groovy\\}
    interval: ${groovy.interval:60}
  db:
    name: test
    url: ${db.yc_base.url:jdbc:mysql://10.180.8.205:3306/yc_base?useUnicode=true&amp;characterEncoding=utf8mb4}
    username: ${db.yc_base.username:root}
    password: ${db.yc_base.pwd:rcs}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    basepackage: com.yonyou.microservice.filter.mapper
    xmlLocation: classpath:mapper/**/*.xml
redis:
  hostName: ${redis.yc_base.ip:10.180.4.221}
  port: ${redis.yc_base.port:6379}
  password: ${redis.yc_base.password:Pass1234}
  timeout: ${redis.yc_base.timeout:10000}
  testWhileIdle: true 
  maxIdle: ${redis.yc_base.maxIdle:300}  
  maxTotal: ${redis.yc_base.maxTotal:1000}  
  maxWaitMillis: ${redis.yc_base.maxWaitMillis:1000}  
  minEvictableIdleTimeMillis: ${redis.yc_base.minEvictableIdleTimeMillis:300000}  
  numTestsPerEvictionRun: ${redis.yc_base.numTestsPerEvictionRun:1024}  
  timeBetweenEvictionRunsMillis: ${redis.yc_base.timeBetweenEvictionRunsMillis:30000}  
  testOnBorrow: ${redis.yc_base.testOnBorrow:true}  
  expire: 2592000